module.exports = Object.freeze({
  HOST: "http://localhost:3000/",
  TAPLINK: "https://copybinback.herokuapp.com/api/public/tapLink/",
  OPENLINK: "https://copybinback.herokuapp.com/api/public/openLink/",
  WEBSITE: "Code>Bin",
  PUBLICCODES: "Public>Codes",
  GENERATELINK: "Generate>Link",
  NUMBERTHEORY: "Number>Theory",
  DEFAULTTHEME: "monokai",
  DEFAULTMODE: "javascript",
  THEMES: [
    "monokai",
    "github",
    "tomorrow",
    "kuroir",
    "twilight",
    "xcode",
    "textmate",
    "solarized_dark",
    "solarized_light",
    "terminal",
  ],
  MODES: [
    "javascript",
    "java",
    "python",
    "xml",
    "ruby",
    "sass",
    "markdown",
    "mysql",
    "json",
    "html",
    "handlebars",
    "golang",
    "csharp",
    "elixir",
    "typescript",
    "css",
  ],
  CALCULATEBUTTONBG: "#51b82a",
  CALCULATEBUTTONTEXTCOLOR: "#fff",
  APPBG: "#d8ffc9",
  HEADINGCOLOR: "#04e000",
  MONOKAI: "#272822",
});
